### PR TITLE
Added radio submix

### PR DESCRIPTION
**Pull request by 1A3Dev**
Added radio submix (with a config option) which adds an effect to people speaking on the radio.

### CODE REVIEW

**Comment by goncalobsccosta** [comment]
From what I tested, the first time players talk in radio, and before talking in radio everything is fine, but after that everyone's voice is laggy and some people can't hear each other...

**Comment by goncalobsccosta** [comment]
I tested with 250 players

**Comment by 1A3Dev** [comment]
> From what I tested, the first time players talk in radio, and before talking in radio everything is fine, but after that everyone's voice is laggy and some people can't hear each other...

I tested it with around 50 players and it did it for the first few days but ended up fixing itself.

**Comment by fkk-cz** [comment]
I'm using rp-radio and having an issue where enabling submix mutes all incoming radio traffic, tried with 3dAudio disabled but same problem. Any ideas?

**Review by DayRK — APPROVED** [review]

**Comment by S3D0N** [comment]
I followed all the steps but nothing changed and everything works but the radio has no filter

**Pull request closed without merging**
